version: '2'
services:
    authent-app:
        image: authent
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://authent-mysql:3306/authent?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    authent-mysql:
        image: 'mysql:5.7.20'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=authent
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    backoffice-app:
        image: backoffice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://backoffice-postgresql:5432/backoffice'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8081'
    backoffice-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=backoffice
            - POSTGRES_PASSWORD=
    
    customer-app:
        image: customer
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://customer-postgresql:5432/customer'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    customer-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=customer
            - POSTGRES_PASSWORD=
    
    document-app:
        image: document
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATA_MONGODB_URI=mongodb://document-mongodb:27017'
            - SPRING_DATA_MONGODB_DATABASE=document
            - JHIPSTER_SLEEP=30
            - 'SPRING_DATA_JEST_URI=http://document-elasticsearch:9200'
            - JHIPSTER_REGISTRY_PASSWORD=admin
    document-mongodb:
        image: 'mongo:4.0.2'
    document-elasticsearch:
        image: 'elasticsearch:5.6.13'
        command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
        environment:
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    
    frontoffice-app:
        image: frontoffice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://frontoffice-postgresql:5432/frontoffice'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8081:8080'
    frontoffice-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=frontoffice
            - POSTGRES_PASSWORD=
    
    notification-app:
        image: notification
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATA_MONGODB_URI=mongodb://notification-mongodb:27017'
            - SPRING_DATA_MONGODB_DATABASE=notification
            - JHIPSTER_SLEEP=30
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin
    notification-mongodb-node:
        build:
            context: ../core/services/notification/src/main/docker
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    notification-mongodb-config:
        image: 'mongo:4.0.2'
        container_name: notification-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
    notification-mongodb:
        image: 'mongo:4.0.2'
        command: mongos --configdb notification-mongodb-config
    
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
            file: jhipster-console.yml
            service: jhipster-logstash
        depends_on:
            - jhipster-elasticsearch
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
        depends_on:
            - jhipster-elasticsearch
    jhipster-import-dashboards:
        extends:
            file: jhipster-console.yml
            service: jhipster-import-dashboards
        depends_on:
            - jhipster-elasticsearch
    jhipster-curator:
        extends:
            file: jhipster-console.yml
            service: jhipster-curator
        depends_on:
            - jhipster-elasticsearch
    jhipster-zipkin:
        extends:
            file: jhipster-console.yml
            service: jhipster-zipkin
        depends_on:
            - jhipster-elasticsearch
